### ISSUE TITLE
Client Credentials flow seems to be missing

### ISSUE THREAD

**Issue by jimAtLoyal** [microsoftgraph/microsoft-graph-docs-contrib#8734] opened 2023-10-19 17:19 UTC
There are three links to this, but they go no where.

https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=csharp#client-credentials-provider

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4537f77e-a8e8-e3f1-9cc4-2fd930db7ada
* Version Independent ID: 46396fa2-f7e2-322e-5e76-f9e2d17d1b48
* Content: [Choose a Microsoft Graph authentication provider - Microsoft Graph](https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=csharp#client-credentials-provider)
* Content Source: [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/sdks/choose-authentication-providers.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MIchaelMainer** [comment] 2023-10-19 21:25
Thank you @jimAtLoyal. I have no idea why we aren't seeing this section being published. I can confirm that the section exists in the source. https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/sdks/choose-authentication-providers.md#client-credentials-provider.

@angelgolfer-ms Do you have any insights into this?

**Comment by lramosvea** [comment] 2024-03-12 20:21
Closing as this seems to be fixed. Thanks.

**Closed by lramosvea** 2024-03-12 20:21 UTC
