### ISSUE TITLE
Missing riskEventType values - Verified threat actor IP and Suspicious sending patterns

### ISSUE THREAD

**Issue by itishnitsa-msft** [microsoftgraph/microsoft-graph-docs-contrib#9114] opened 2024-02-13 15:59 UTC
There are 25 risk types documented in https://learn.microsoft.com/en-us/entra/id-protection/concept-identity-protection-risks. But only 21 are listed in this article. Verified threat actor IP and Suspicious sending patterns are missing and two others.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ce56fe4-b5f4-cdde-1f35-39091aaa6303
* Version Independent ID: b07140db-8b54-e375-bbb8-1506aa0e616f
* Content: [riskDetection resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/riskdetection.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @ebasseri
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2024-02-14 09:02
Thank you @itishnitsa-msft for reporting this issue.

@ebasseri - Can you help confirm and document the Microsoft Graph names for the missing risk detections? Thanks.

**Comment by FaithOmbongi** [comment] 2024-02-15 14:11
Tracking this issue via internal bug 2799638 that's assigned to @ebasseri. Duplicate of https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/64

**Comment by FaithOmbongi** [comment] 2024-03-01 09:04
Closing this issue in readiness for deactivation of GitHub issues. See this post for more information https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/9146.

We'll track the issue via the internal bug.

**Closed by FaithOmbongi** 2024-03-01 09:04 UTC
Labels: area: Entra, area: identity protection, awaiting internal response, bug: product
