### ISSUE TITLE
Can't find the ID needed as a parameter

### ISSUE THREAD

**Issue by RomainBitard** [microsoftgraph/microsoft-graph-docs-contrib#8525] opened 2023-09-05 15:36 UTC
There is nothing that references the ID {internalDomainFederationId} on this page, where to find it, what is it ? 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eec10160-db1c-855e-2dcb-2f777e3fdd01
* Version Independent ID: d6247e49-f233-2455-8c8a-34cc3c597390
* Content: [Get internalDomainFederation - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/internaldomainfederation-get.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @rahul-nagraj
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2023-09-06 07:32
Thank you @RomainBitard for raising this issue. When you [Create federationConfiguration](https://learn.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-beta&tabs=http), you get the ID back and that's the one you use for the GET, UPDATE, and DELETE operations. However, I see there's no LIST operation which would have been the easiest way to retrieve the ID of the object you want to manage. @rahul-nagraj - Isn't the LIST operation supported by this API?

**Comment by RomainBitard** [comment] 2023-09-06 08:09
Thanks for the reply @FaithOmbongi I wasn't sure if it was the same ID (I was planning to test it though :D). 
I posted this issue because I didn't see a list operation too, and no mention of the ID in the documentation ! 
Thanks again for clarifying !

**Comment by rahul-nagraj** [comment] 2023-09-07 14:37
Hey @RomainBitard ,
Thanks for sharing this. This is correct. A get operation on  /domains/{domainsId}/federationConfiguration/ will get you all the internalDomainFederationIds. We have a work item to update the docs. It will be updated shortly. 
Thank you again for bringing this to our notice.

Regards,
Rahul Nagraj

**Comment by FaithOmbongi** [comment] 2023-09-07 15:29
Great. Thanks, @RomainBitard, @rahul-nagraj for confirming that the LIST operation (GET /domains/{domainsId}/federationConfiguration) is supported. We'll close this issue once the doc is live.

**Comment by mbukovich** [comment] 2023-10-05 18:57
To add to this discussion, both I and one of our customers were not able to use the suggested list query to retrieve a list of federation configurations. We received the error message:

{
    "error": {
        "code": "Request_ResourceNotFound",
        "message": "Resource 'federationConfiguration' does not exist or one of its queried reference-property objects are not present.",
        "innerError": {
            "date": "2023-10-05T18:53:47",
            "request-id": "7e657ecc-81a2-4885-8d98-f8984705f4c7",
            "client-request-id": "7c6db929-9e82-c4f7-851c-cd2869ab1d38"
        }
    }
}


{
    "error": {
        "code": "Request_ResourceNotFound",
        "message": "Resource 'federationConfiguration' does not exist or one of its queried reference-property objects are not present.",
        "innerError": {
            "date": "2023-10-05T17:07:26",
            "request-id": "ad436199-8cff-4514-9692-a30ec7b3df59",
            "client-request-id": "aab3ff22-dd63-5257-3aaa-a7004593c070"
        }
    }
}

@rahul-nagraj is the list API to no longer be supported?

**Comment by FaithOmbongi** [comment] 2023-10-06 07:33
@rahul-nagraj - I've repro'd the same behavior. I didn't confirm whether the LIST operation was supported before, but it isn't supported now.

<img width="800" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/14026935/a6a77573-14b6-41b7-980e-eb2717c878ff">


@mbukovich - Unfortunately, this forum is only for documentation-related issues but [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/306/microsoft-graph-extensions-api) is the best forum to investigate, resolve, and answer this functionality question. I recommend that you file your question there. Please share the same payloads you've shared as they contain the request ID that will be helpful for investigations.

**Comment by mbukovich** [comment] 2023-10-09 17:40
@FaithOmbongi 
Thanks for the feedback! It turns out the Customer was able to use the list query after properly setting up a federationConfiguration. It seems that if there are no federationConfigurations available the query fails, but if there are, then a list will be returned. 

The reason I felt it was relevant to discuss in a docs issue is that it is related to whether or not the list query is supported (which will need to be documented).

**Comment by FaithOmbongi** [comment] 2023-10-09 18:01
Thank you for the feedback @mbukovich. As for your comment about the API behavior when no configuration exists:

 > It seems that if there are no federationConfigurations available the query fails, but if there are, then a list will be returned.

Can you confirm whether the error is a `404 Not Found` or was it a `400 Bad Request` error?

cc @rahul-nagraj to document the LIST API.

**Comment by mbukovich** [comment] 2023-10-09 18:12
The error code was 404

**Comment by FaithOmbongi** [comment] 2023-10-09 18:17
> The error code was 404

Ah, OK. I think 404 Not Found is acceptable if an object is missing. @rahul-nagraj , please advise if this error code might cause confusion for a LIST operation, as opposed to 200 OK with an empty response body?

Regardless, we'll be sure to add this error code in the LIST doc in case the API keeps returning the error code. Thanks @mbukovich.

**Comment by mbukovich** [comment] 2023-10-09 18:27
More than happy to help and contribute where I can, and I enjoy participating in these discussions!

My own personal feedback is that most LIST queries I have worked with in Microsoft Graph will return a 200 OK with an empty response body (or at least empty "value" array). I personally believe that the most consistent and least confusing behavior would be a 200 with empty response body or "value" property.

**Comment by FaithOmbongi** [comment] 2023-10-31 09:33
The [LIST internalDomainFederations](https://learn.microsoft.com/en-us/graph/api/domain-list-federationconfiguration?view=graph-rest-1.0&tabs=http) doc is now live. Closing this issue and marking it as resolved.

**Closed by FaithOmbongi** 2023-10-31 09:33 UTC
Labels: area: directory management, area: Entra, area: identity, awaiting internal response, request: documentation

**Comment by rahul-nagraj** [comment] 2023-11-06 11:16
Thanks for the update @FaithOmbongi.
And yes I can confirm that 404 Not Found is returned if there is not Federation Configuration on the tenant.
