### ISSUE TITLE
serviceProvisioningErrors does not support $filter

### ISSUE THREAD

**Issue by manuel-falcao-magalhaes** [microsoftgraph/microsoft-graph-docs-contrib#8802] opened 2023-11-08 15:55 UTC
The serviceProvisioningErrors property, according to the orgContact resource type (beta) documentation:

"Errors published by a federated service describing a non-transient, service-specific error regarding the properties or link from an orgContact object .
Supports $filter (eq, not, for isResolved and serviceInstance)."

However, it seems that it doesn't support filter.

Two examples with $count=true and with the ConsistencyLevel header = eventual:

Request: "GET https://graph.microsoft.com/beta/contacts?$filter=serviceProvisioningErrors/any(x: x/isResolved eq false)&$count=true"
Response:

{
"error": {
"code": "Request_UnsupportedQuery",
"message": "Unsupported query.",
}
}

Request: "GET https://graph.microsoft.com/beta/contacts?$filter=not(serviceProvisioningErrors/any(x: x/isResolved eq true))&$count=true"
Response:

{
"error": {
"code": "Request_UnsupportedQuery",
"message": "Unsupported query.",
}
}

Furthermore, the serviceProvisioningErrors property is not in the "Advanced query capabilities on Microsoft Entra ID objects" documentation page: https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http

(related to this issue https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8789)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb66a5c-0028-3a06-964f-c7a82055365b
* Version Independent ID: 6d5e2f12-0ff8-977b-2765-f6bebbf73eff
* Content: [orgContact resource type - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/resources/orgcontact.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2023-11-15 18:04
Closing as a duplicate of https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8803

**Closed** 2023-12-01 14:55 UTC
Labels: area: Entra, area: query parameters
