### ISSUE TITLE
Does systemPreferredAuthenticationMethods support filtering?

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#9060] opened 2024-01-27 18:24 UTC
According to the doc, `systemPreferredAuthenticationMethods` should support filter with `any` operator, but it returns the error.

```
GET /v1.0/reports/authenticationMethods/userRegistrationDetails?$filter=systemPreferredAuthenticationMethods/any(m:m eq 'oath')
{
    "error": {
        "code": "UnknownError",
        "message": "Unable to find nonEntity type name",
        "innerError": {
            "date": "2024-01-27T18:17:13",
            "request-id": "7bece12c-6281-4dc3-9954-edf5d60d94ba",
            "client-request-id": "9248fee4-4068-b24f-8391-f5e1bae5acca"
        }
    }
}
```

Please, update the doc if filtering by `systemPreferredAuthenticationMethods` is not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb6298e9-2b80-cad5-15ee-948ba6a35a03
* Version Independent ID: 7d221f54-e79e-1ef5-8d1f-a88114055ac1
* Content: [userRegistrationDetails resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/userregistrationdetails?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/userregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/userregistrationdetails.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @egreenberg14 
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2024-03-01 09:12
Closing this issue in readiness for deactivation of GitHub issues. See this post for more information https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/9146.

I'm following up with @kvenkit for confirmation.

**Closed by FaithOmbongi** 2024-03-01 09:12 UTC
Labels: area: Entra, area: query parameters, area: reports, awaiting internal response

**Comment by FaithOmbongi** [comment] 2024-03-06 07:52
UPDATE: @kvenkit has confirmed the issue is a known product bug and the engineering team is working to fix it.
