### ISSUE TITLE
"Directory.AccessAsUser.All" Permission Scope Required!

### ISSUE THREAD

**Issue by majoradhd** [microsoftgraph/microsoft-graph-docs-contrib#8747] opened 2023-10-25 01:20 UTC
When running "New-MgDomainFederationConfiguration" PowerShell Command I had the following scopes and was getting a 403 unauthorized error. 
Scopes: 
Directory.ReadWrite.All
Domain.ReadWrite.All
openid
profile
Sites.FullControl.All
User.Read
email 

After adding the "Directory.AccessAsUser.All" permission scope to my break-glass admin account I was able to successfully create the federated domain configuration using the Microsoft Graph PowerShell Module. 

Please update the documentation to reflect these recent changes. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc45e9cc-5d66-5d5e-13d7-f9629b478bd8
* Version Independent ID: 1cdec7f7-c9ae-9afb-e857-51a335067471
* Content: [Create federationConfiguration - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/domain-post-federationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/domain-post-federationconfiguration.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @rahul-nagraj
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2023-10-26 07:58
Hi @rahul-nagraj - please advise.

Similar to https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/1511 and also tracked via engineer bug 2359161 that's assigned to Avinash.

**Comment by FaithOmbongi** [comment] 2024-03-01 08:31
UPDATE: Since fixing the issue is taking a bit longer than we hoped, I've documented a known issue and added a note in the documentation for the affected WRITE operations recommending *Directory.AccessAsUser.All* as a temporary workaround.

Please be on the lookout for when the issue is fixed so you can remove the use of the permission which is too highly privileged.

**Closed by FaithOmbongi** 2024-03-01 08:31 UTC
Labels: area: Entra, area: permissions, awaiting internal response, bug: product, potential known issue, Bug#2359161
