### ISSUE TITLE
Teams graph api is not supported in Gallatin Teams (China operated by 21Vianet)

### ISSUE THREAD

**Issue by XixiHuang333** [microsoftgraph/microsoft-graph-docs-contrib#8637] opened 2023-09-28 06:01 UTC
[Enter feedback here]

Hello team,
Teams graph api is not supported in Gallatin Teams (China operated by 21Vianet).
In fiddler log:
{"error":{"code":"InternalServerError","message":"Failed to process request.","innerError":{"date":"2023-09-28T01:29:13","request-id":"a35fa201-5608-4689-a2d3-7fc4aa4120a6","client-request-id":"a35fa201-5608-4689-a2d3-7fc4aa4120a6"}}}

In document: Microsoft Teams operated by 21Vianet

https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/teams-operated-by-21vianet

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/40224592/75f509fa-0aed-4c9b-80d9-ebda3695dbcc)

Please help to verify and change the checkbox as below:

<img width="285" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/40224592/bbea8b9e-2ac4-4597-a878-3a992391372e">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f67cabe4-bade-9a07-90ec-15adaeab3de2
* Version Independent ID: dfbbddfe-f113-1ae1-9d21-77ab976ddc20
* Content: [Get chatMessageHostedContent - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/chatmessagehostedcontent-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abshar-teams** [comment] 2023-10-06 19:58
@XixiHuang333 
its a documentation bug. I will work on fixing it. The Get chatMessageHostedContent is supported in Gallatin, but it only works in Delegated context, not application context.

**Comment by abshar-teams** [comment] 2023-10-06 19:59
Duplicate of https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8634

**Closed by abshar-teams** 2023-10-06 19:59 UTC
