### ISSUE TITLE
Required permissions outdated

### ISSUE THREAD

**Issue by rajarajacholank** [microsoftgraph/microsoft-graph-docs-contrib#8996] opened 2024-01-08 06:51 UTC
It appears to be the document is outdated as required permission for the api GET https://graph.microsoft.com/v1.0/users User.Read.All results in error. Many users have the same problem. Please update the document with the exact permissions required. It will save our time and efforts.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04f96510-c628-47f8-971f-d5ba7b560efc
* Version Independent ID: f27f8646-1313-f225-b315-1ae3bc036117
* Content: [Get access without a user - Microsoft Graph](https://learn.microsoft.com/en-us/graph/auth-v2-service?tabs=http)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/auth-v2-service.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment] 2024-01-30 07:43
Thank you @rajarajacholank for raising this issue. Unfortunately, I've retested the steps in the article and unable to reproduce your error.  I confirm that [_User.Read.All_ is the minimum application permission required to enumerate users in a tenant](https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#permissions). Here's a screenshot of the roles in my decoded app-only token which I successfully used to retrieve users.

<img width="457" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/14026935/3bb9cf51-61ae-45ab-a4e2-28945a6e543b">

 If you're still unable to call the API, please file a bug at [Microsoft Graph Q&A](https://aka.ms/ge) and provide a request ID for investigation. Closing this issue here for now.

**Closed by FaithOmbongi** 2024-01-30 07:43 UTC
Labels: area: Entra, area: permissions
